version: "3.9"
services:
  db:
    image: mariadb:10.8.3-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: glg203
      MARIADB_DATABASE: petstore09


